In [1]:
import pandas as pd

In [13]:
df = pd.read_csv('./data/raw/ai_fat_pilot_16oct25.csv')

In [14]:
df.head()

,participant.id_in_session,participant.code,participant.label,participant._is_bot,participant._index_in_pages,participant._max_page_index,participant._current_app_name,participant._current_page_name,participant.time_started_utc,participant.visited,...,_5_feedback.1.player.srsi_use_me,_5_feedback.1.player.srsi_use_me_justification,_5_feedback.1.player.ai_use,_5_feedback.1.player.feedback,_5_feedback.1.player.check,_5_feedback.1.player.prolific_id,_5_feedback.1.player.recaptcha_token,_5_feedback.1.player.recaptcha_score,_5_feedback.1.group.id_in_subsession,_5_feedback.1.subsession.round_number
0,1,vvv59zr0,628f83dc5398c04bac86f9e6,0,16,16,_5_feedback,p13_thanks,2025-10-16 13:59:18.052570,1,...,yes,NaN,yes,none,NaN,628f83dc5398c04bac86f9e6,0cAFcWeA5ANNFcv0mXIpyNrPo5Jad-fkoFzw5rZF5kIg4Y...,0.9,1,1
1,2,o1tewpz9,55ed87f0748092000baa9a0b,0,16,16,_5_feedback,p13_thanks,2025-10-16 13:59:41.735543,1,...,yes,NaN,yes,No comment,NaN,55ed87f0748092000baa9a0b,0cAFcWeA5VlmPszPieDBhthScAnbsJZKzzjZeMoiBVjq7s...,0.9,1,1
2,3,t9s5s6a4,5fefefa4c9707d3516361c9c,0,3,16,_2_main,p1_associations,2025-10-16 13:59:42.032602,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1
3,4,ynd1a9u2,612fde55d251a3547b8e5766,0,16,16,_5_feedback,p13_thanks,2025-10-16 13:59:42.348762,1,...,yes,NaN,yes,N.a,NaN,612fde55d251a3547b8e5766,0cAFcWeA74nM6Gpatc9Mq5amSFGb_tJGw6k2t3opKv00yr...,0.9,1,1
4,5,vp6m46ud,6110888158573651261c3100,0,3,16,_2_main,p1_associations,2025-10-16 14:00:23.734433,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1

In [15]:
# drop rows where partcipant._current_page_name is not p13_thanks
df = df[df['participant._current_page_name'] == 'p13_thanks']

In [16]:
df.columns

Index(['participant.id_in_session', 'participant.code', 'participant.label',
       'participant._is_bot', 'participant._index_in_pages',
       'participant._max_page_index', 'participant._current_app_name',
       'participant._current_page_name', 'participant.time_started_utc',
       'participant.visited', 'participant.mturk_worker_id',
       'participant.mturk_assignment_id', 'participant.payoff',
       'participant.associations', 'session.code', 'session.label',
       'session.mturk_HITId', 'session.mturk_HITGroupId', 'session.comment',
       'session.is_demo', 'session.config.real_world_currency_per_point',
       'session.config.prolific_completion_link',
       'session.config.recaptcha_site_key',
       'session.config.prolific_no_consent_link', 'session.config.name',
       'session.config.recaptcha_secret_key',
       'session.config.participation_fee', '_1_consent.1.player.id_in_group',
       '_1_consent.1.player.role', '_1_consent.1.player.payoff',
       '_1_consent.1.player.consent', '_1_consent.1.group.id_in_subsession',
       '_1_consent.1.subsession.round_number', '_2_main.1.player.id_in_group',
       '_2_main.1.player.role', '_2_main.1.player.payoff',
       '_2_main.1.player.association1', '_2_main.1.player.association2',
       '_2_main.1.player.association3', '_2_main.1.player.association4',
       '_2_main.1.player.association5', '_2_main.1.group.id_in_subsession',
       '_2_main.1.subsession.round_number',
       '_2_main.1.subsession.prolific_completion_link',
       '_2_main.1.subsession.prolific_no_consent_link',
       '_3_exit_questions.1.player.id_in_group',
       '_3_exit_questions.1.player.role', '_3_exit_questions.1.player.payoff',
       '_3_exit_questions.1.player.ai_trust',
       '_3_exit_questions.1.player.ai_risk',
       '_3_exit_questions.1.player.daily_ai_use',
       '_3_exit_questions.1.player.ai_expertise',
       '_3_exit_questions.1.player.ai_expertise_justification',
       '_3_exit_questions.1.group.id_in_subsession',
       '_3_exit_questions.1.subsession.round_number',
       '_4_demographics.1.player.id_in_group', '_4_demographics.1.player.role',
       '_4_demographics.1.player.payoff', '_4_demographics.1.player.age',
       '_4_demographics.1.player.gender',
       '_4_demographics.1.player.gender_self_describe',
       '_4_demographics.1.player.illusion_response',
       '_4_demographics.1.group.id_in_subsession',
       '_4_demographics.1.subsession.round_number',
       '_5_feedback.1.player.id_in_group', '_5_feedback.1.player.role',
       '_5_feedback.1.player.payoff', '_5_feedback.1.player.srsi_use_me',
       '_5_feedback.1.player.srsi_use_me_justification',
       '_5_feedback.1.player.ai_use', '_5_feedback.1.player.feedback',
       '_5_feedback.1.player.check', '_5_feedback.1.player.prolific_id',
       '_5_feedback.1.player.recaptcha_token',
       '_5_feedback.1.player.recaptcha_score',
       '_5_feedback.1.group.id_in_subsession',
       '_5_feedback.1.subsession.round_number'],
      dtype='object')

In [17]:
# remove columns that are not needed
cols_to_remove = ['participant._is_bot', 'participant._index_in_pages',
       'participant._max_page_index', 'participant._current_app_name','participant.visited', 'participant.mturk_worker_id',
       'participant.mturk_assignment_id', 'participant.payoff', 'session.code', 'session.label',
       'session.mturk_HITId', 'session.mturk_HITGroupId', 'session.comment',
       'session.is_demo', 'session.config.real_world_currency_per_point',
       'session.config.prolific_completion_link',
       'session.config.recaptcha_site_key',
       'session.config.prolific_no_consent_link', 'session.config.name',
       'session.config.recaptcha_secret_key',
       'session.config.participation_fee', '_1_consent.1.player.id_in_group',
       '_1_consent.1.player.role', '_1_consent.1.player.payoff', '_1_consent.1.group.id_in_subsession',
       '_1_consent.1.subsession.round_number', '_2_main.1.player.id_in_group',
       '_2_main.1.player.role', '_2_main.1.player.payoff', '_2_main.1.group.id_in_subsession',
       '_2_main.1.subsession.round_number',
       '_2_main.1.subsession.prolific_completion_link',
       '_2_main.1.subsession.prolific_no_consent_link',
       '_3_exit_questions.1.player.id_in_group',
       '_3_exit_questions.1.player.role', '_3_exit_questions.1.player.payoff', '_3_exit_questions.1.group.id_in_subsession',
       '_3_exit_questions.1.subsession.round_number',
       '_4_demographics.1.player.id_in_group', '_4_demographics.1.player.role',
       '_4_demographics.1.player.payoff', '_4_demographics.1.group.id_in_subsession',
       '_4_demographics.1.subsession.round_number',
       '_5_feedback.1.player.id_in_group', '_5_feedback.1.player.role',
       '_5_feedback.1.player.payoff', '_5_feedback.1.player.recaptcha_token', '_5_feedback.1.group.id_in_subsession',
       '_5_feedback.1.subsession.round_number']
df = df.drop(columns=cols_to_remove)

In [ ]:
# rename columns to keep only last part after last dot
df.columns = [col.split('.')[-1] for col in df.columns]

,id_in_session,code,label,_current_page_name,time_started_utc,associations,consent,association1,association2,association3,...,gender,gender_self_describe,illusion_response,srsi_use_me,srsi_use_me_justification,ai_use,feedback,check,prolific_id,recaptcha_score
0,1,vvv59zr0,628f83dc5398c04bac86f9e6,p13_thanks,2025-10-16 13:59:18.052570,"{'association1': 'reliable', 'association2': '...",1.0,reliable,fast,convenient,...,male,NaN,duck,yes,NaN,yes,none,NaN,628f83dc5398c04bac86f9e6,0.9
1,2,o1tewpz9,55ed87f0748092000baa9a0b,p13_thanks,2025-10-16 13:59:41.735543,"{'association1': 'cognition', 'association2': ...",1.0,cognition,reasoning,technology,...,male,NaN,duck,yes,NaN,yes,No comment,NaN,55ed87f0748092000baa9a0b,0.9
3,4,ynd1a9u2,612fde55d251a3547b8e5766,p13_thanks,2025-10-16 13:59:42.348762,"{'association1': 'Chat gpt', 'association2': '...",1.0,Chat gpt,Efficiency,Smart,...,male,NaN,Duck,yes,NaN,yes,N.a,NaN,612fde55d251a3547b8e5766,0.9
5,6,ldwme93h,6650a38d75c08f70233642b1,p13_thanks,2025-10-16 14:00:49.266817,"{'association1': 'make life easier', 'associat...",1.0,make life easier,take away jobs,new opportunities,...,male,NaN,duck,yes,NaN,no,NaN,NaN,6650a38d75c08f70233642b1,0.9
6,7,vqi0l8vw,614dd304ed948bbfe8c22215,p13_thanks,2025-10-16 14:01:02.582087,"{'association1': 'Smart', 'association2': 'Fak...",1.0,Smart,Fake,Scary,...,female,NaN,duck,yes,NaN,no,N/a,NaN,614dd304ed948bbfe8c22215,0.9
7,8,a3ybdhvo,5cd31d68db60cb0017d4ac33,p13_thanks,2025-10-16 14:01:23.712350,"{'association1': 'scary', 'association2': 'ove...",1.0,scary,overtaking,Isaac Asimov,...,female,NaN,duck,yes,NaN,no,I know there's a famous optical illusion regar...,NaN,5cd31d68db60cb0017d4ac33,0.9
8,9,ripw9l2o,66eb1a41306925cf993d6490,p13_thanks,2025-10-16 14:01:27.917716,"{'association1': 'Possibilities ', 'associatio...",1.0,Possibilities,Fear,Positive outcomes,...,male,NaN,duck,yes,NaN,no,No comment.,NaN,66eb1a41306925cf993d6490,0.9
9,10,u96eqlti,6631056349b08a35aae1ac5f,p13_thanks,2025-10-16 14:02:18.959893,"{'association1': 'Climate catastrophe ', 'asso...",1.0,Climate catastrophe,Water usage,Art theft,...,non_binary,NaN,Duck,yes,NaN,no,No feedback,NaN,6631056349b08a35aae1ac5f,0.9
12,13,8j6g95br,6021522cc0eec00d2e4ab6c7,p13_thanks,2025-10-16 14:05:46.672945,"{'association1': 'glorified search engine', 'a...",1.0,glorified search engine,next dot com bubble,highly useful,...,non_binary,NaN,duck,yes,NaN,no,No,NaN,6021522cc0eec00d2e4ab6c7,0.9
13,14,rn6vgoso,67f015260f679212b3c34caa,p13_thanks,2025-10-16 14:06:08.287226,"{'association1': 'Efficient', 'association2': ...",1.0,Efficient,Smart/intelligent,convinient,...,female,NaN,a duck,yes,NaN,no,no comment,NaN,67f015260f679212b3c34caa,0.9
14,15,kdo08osb,66d1fdd400acfdbc181f41e0,p13_thanks,2025-10-16 14:07:23.191774,"{'association1': 'chat gpt', 'association2': '...",1.0,chat gpt,chat bot,hallucinations,...,male,NaN,duck,yes,NaN,no,none,NaN,66d1fdd400acfdbc181f41e0,0.9
15,16,c3mm7fkp,615914a33224dc31f1045612,p13_thanks,2025-10-16 14:09:04.661048,"{'association1': 'Intelligent ', 'association2...",1.0,Intelligent,problem solver,the future,...,male,NaN,duck,yes,NaN,no,Thank you,NaN,615914a33224dc31f1045612,0.9
16,17,9jqku76a,5df4ed2eae7b303760a9d47c,p13_thanks,2025-10-16 14:09:55.404611,"{'association1': 'gemini', 'association2': 'mi...",1.0,gemini,midjourney,leonardo,...,female,NaN,duck,yes,NaN,no,thanks,NaN,5df4ed2eae7b303760a9d47c,0.9
17,18,k8wljbmv,62349dcdec7c3f8e7e1bc90b,p13_thanks,2025-10-16 14:10:51.986645,"{'association1': 'computers', 'association2': ...",1.0,computers,algorythm,machine learning,...,female,NaN,duck,yes,NaN,no,Straightforward study. No issues,NaN,62349dcdec7c3f8e7e1bc90b,0.9
18,19,4zltjmsn,5c9ebf067114700016da2813,p13_thanks,2025-10-16 14:12:24.205067,"{'association1': 'copying', 'association2': 'f...",1.0,copying,fake,crawling the web,...,male,NaN,duck,yes,NaN,no,none,NaN,5c9ebf067114700016da2813,0.9
19,20,wqz6cuom,674530631263934b181d3224,p13_thanks,2025-10-16 14:12:41.640796,"{'association1': 'Creative writing', 'associat...",1.0,Creative writing,Brainstorming,Productivity,...,male,NaN,duck,yes,NaN,no,Thank you for the opportunity.,NaN,674530631263934b181d3224,0.9
21,22,kss94mwy,5c28dd50da51990001e31d86,p13_thanks,2025-10-16 14:13:40.236993,"{'association1': 'Intelligent', 'association2'...",1.0,Intelligent,Creative,Useful,...,male,NaN,duck,yes,NaN,no,Thank you.,NaN,5c28dd50da51990001e31d86,0.9
22,23,pll21c4s,66cec5a3fdf1fe2c010e9971,p13_thanks,2025-10-16 14:14:47.713525,{'association1': 'it is the assit of computers...,1.0,it is the assit of computers,use of machine to make deccisions,assit in various task,...,female,NaN,duck,yes,NaN,no,no comments,NaN,66cec5a3fdf1fe2c010e9971,0.7
23,24,xaqlzx4z,66bdf79c29a4dd71ff4de0d0,p13_thanks,2025-10-16 14:21:41.841668,"{'association1': 'technology', 'association2':...",1.0,technology,futuristic,helpful,...,female,NaN,duck,yes,NaN,no,none,NaN,66bdf79c29a4dd71ff4de0d0,0.9
24,25,7wyifw91,66f9a40196d53f05f2232cff,p13_thanks,2025-10-16 14:42:05.107078,"{'association1': 'technology', 'association2':...",1.0,technology,future,advanced tech,...,female,NaN,duck,yes,NaN,no,Thanks for the opportunity to participate!,NaN,66f9a40196d53f05f2232cff,0.9

In [23]:
df.columns

Index(['id_in_session', 'code', 'label', '_current_page_name',
       'time_started_utc', 'associations', 'consent', 'association1',
       'association2', 'association3', 'association4', 'association5',
       'ai_trust', 'ai_risk', 'daily_ai_use', 'ai_expertise',
       'ai_expertise_justification', 'age', 'gender', 'gender_self_describe',
       'illusion_response', 'srsi_use_me', 'srsi_use_me_justification',
       'ai_use', 'feedback', 'check', 'prolific_id', 'recaptcha_score'],
      dtype='object')

In [24]:
# rename srsi_use_me to include_data and srsi_use_me_justification to include_data_justification
df = df.rename(columns={'srsi_use_me': 'include_data', 'srsi_use_me_justification': 'include_data_justification'})

# rename check to honeypot_checkbox
df = df.rename(columns={'check': 'honeypot_checkbox'})

# rename ai_use to ai_use_survey
df = df.rename(columns={'ai_use': 'ai_use_survey'})

In [25]:
df.head()

,id_in_session,code,label,_current_page_name,time_started_utc,associations,consent,association1,association2,association3,...,gender,gender_self_describe,illusion_response,include_data,include_data_justification,ai_use_survey,feedback,honeypot_checkbox,prolific_id,recaptcha_score
0,1,vvv59zr0,628f83dc5398c04bac86f9e6,p13_thanks,2025-10-16 13:59:18.052570,"{'association1': 'reliable', 'association2': '...",1.0,reliable,fast,convenient,...,male,NaN,duck,yes,NaN,yes,none,NaN,628f83dc5398c04bac86f9e6,0.9
1,2,o1tewpz9,55ed87f0748092000baa9a0b,p13_thanks,2025-10-16 13:59:41.735543,"{'association1': 'cognition', 'association2': ...",1.0,cognition,reasoning,technology,...,male,NaN,duck,yes,NaN,yes,No comment,NaN,55ed87f0748092000baa9a0b,0.9
3,4,ynd1a9u2,612fde55d251a3547b8e5766,p13_thanks,2025-10-16 13:59:42.348762,"{'association1': 'Chat gpt', 'association2': '...",1.0,Chat gpt,Efficiency,Smart,...,male,NaN,Duck,yes,NaN,yes,N.a,NaN,612fde55d251a3547b8e5766,0.9
5,6,ldwme93h,6650a38d75c08f70233642b1,p13_thanks,2025-10-16 14:00:49.266817,"{'association1': 'make life easier', 'associat...",1.0,make life easier,take away jobs,new opportunities,...,male,NaN,duck,yes,NaN,no,NaN,NaN,6650a38d75c08f70233642b1,0.9
6,7,vqi0l8vw,614dd304ed948bbfe8c22215,p13_thanks,2025-10-16 14:01:02.582087,"{'association1': 'Smart', 'association2': 'Fak...",1.0,Smart,Fake,Scary,...,female,NaN,duck,yes,NaN,no,N/a,NaN,614dd304ed948bbfe8c22215,0.9

In [29]:
# rename _current_page_name to finished and set all values to True
df = df.rename(columns={'_current_page_name': 'finished'})
df['finished'] = True

In [30]:
# save to new csv
df.to_csv('./data/clean/ai_fat_pilot_16oct25.csv', index=False)